### ISSUE TITLE
Python-like formatting

### ISSUE THREAD

**Issue by ChristianPanov** [ChristianPanov/lwlog#11]
I am not going to use FMT for that since I don't want any external dependencies. For that reason, I am going to rely on C++20's std::format. As soon as it gets implemented in MSVC, such formatting capability should be implemented in lwlog

**Comment by smalls12** [comment]
std::format would restrict the project to C++20.
You can make this configurable so the user can decide which library they want to use as a backend.

**Comment by ChristianPanov** [comment]
Yes sorry for not elaborating on it. It will definitely be backward compatible with FMT.
