### ISSUE TITLE
Truncated aligned string

### ISSUE THREAD

**Issue by zhtmalxh** [ChristianPanov/lwlog#46]
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.42.34433.0 (but same result even with VS2019)

**To Reproduce**
add left or right alignment in sandbox.cpp, for example:

console->set_pattern(".red([%T] [:**<10**%n]) .dark_green([%l]): .cyan(%v) TEXT");

**Expected**
[18:58:48] [CONSOLE   ] [critical]: First critical message TEXT
(4 white space after console)

**Observed**
[18:58:48] [ONSOLE   ] [critical]: First critical message TEXT
(3 white space after console and first character eliminated)

**Possible error**
I just started looking at this project, I know very little about it but if I break this block in two:

	const std::string_view aligned{ alignment_formatter::align(
		pattern.substr(flag_pos + flag_size, to_align_size), 
		alignment_flag_info.width, 
		alignment_flag_info.fill_char, 
		alignment_flag_info.side
	) };

from ...\lwlog\src\details\pattern\alignment_formatter.cpp getting this:

    auto s = alignment_formatter::align(
      pattern.substr(flag_pos + flag_size, to_align_size),
      alignment_flag_info.width,
      alignment_flag_info.fill_char,
      alignment_flag_info.side
    );

    const std::string_view aligned{ s };

the expected result is correct.

**Comment by ChristianPanov** [comment]
Thank you for opening the issue, I might have an idea at what point it stopped working correctly. I'll be busy with work the following days but I'll try to close it by the end of the week.

If you have any questions regarding the library or you spot some other kind of problem, feel free to write

Thanks
