### ISSUE TITLE
Build on platforms other than Windows

### ISSUE THREAD

**Issue by friendlyanon** [ChristianPanov/lwlog#7]
Mentioned in #6 with some help regarding this.

Opening an issue for tracking.

**Comment by smalls12** [comment]
I am able to build the dev branch on Ubuntu 20.04 with gcc 9.3.0.
I had to make some changes that may not be ideal or wanted mainly fixing some of the forward declarations.

I also added into the cmake infrastructure the example from the README.md.

**Comment by ChristianPanov** [comment]
Thank you for the information. The CMake structure of the project is still under revision. It needs to be polished before I merge it with the main branch.

**Comment by mark-nick-o** [comment]
i tried on ubuntu and i modified some of the library paths that gave me error as well as #include <filesystem> to #include <experimental/filesystem>
compiling with either g++-8/g++-7 -std=c++17 log_test.cpp -o log_test -lstdc++fs

errors like this
lwlog/src/policy/../sinks/../level.h:9:13: error: use of enum ‘level’ without previous declaration
  enum class level : std::uint8_t
             ^~~~~
lwlog/src/policy/../sinks/../level.h:9:19: error: expected unqualified-id before ‘:’ token
  enum class level : std::uint8_t
                   ^
lwlog/src/policy/../sinks/../level.h:20:12: error: ‘level’ does not name a type
  constexpr level operator|(level lhs, level rhs)
            ^~~~~
lwlog/src/policy/../sinks/../level.h:28:12: error: ‘level’ does not name a type
  constexpr level operator&(level lhs, level rhs)
            ^~~~~
lwlog/src/policy/../sinks/../level.h:39:27: error: ‘level’ was not declared in this scope
  constexpr bool has_level(level lhs, level rhs)

lwlog/src/policy/../sinks/../details/pattern/../os.h:19:45: error: ‘__SYS_gettid’ was not declared in this scope
   return static_cast<std::size_t>(::syscall(__SYS_gettid));
                                             ^~~~~~~~~~~~
lwlog/src/policy/../sinks/../details/pattern/../os.h:19:45: note: suggested alternative: ‘SYS_gettid’
   return static_cast<std::size_t>(::syscall(__SYS_gettid));
                                             ^~~~~~~~~~~~
                                             SYS_gettid
In file included from lwlog/src/policy/../sinks/../details/pattern/pattern.h:8,
                 from lwlog/src/policy/../sinks/sink.h:4,
                 from lwlog/src/policy/log_policy.h:3,
                 from lwlog/src/logger.h:3,
                 from lwlog/lwlog.h:3,
                 from log_test.cpp:1:
lwlog/src/policy/../sinks/../details/pattern/../log_message.h: At global scope:
lwlog/src/policy/../sinks/../details/pattern/../log_message.h:28:9: error: declaration of ‘lwlog::level lwlog::details::log_message::level’ [-fpermissive]
   level level;

im using ubuntu WSL on this machine
Linux DESKTOP-M4HNI3V 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ChristianPanov** [comment]
> i tried on ubuntu and i modified some of the library paths that gave me error as well as #include to #include <experimental/filesystem> compiling with either g++-8/g++-7 -std=c++17 log_test.cpp -o log_test -lstdc++fs
> 
> errors like this lwlog/src/policy/../sinks/../level.h:9:13: error: use of enum ‘level’ without previous declaration enum class level : std::uint8_t ^~~~~ lwlog/src/policy/../sinks/../level.h:9:19: error: expected unqualified-id before ‘:’ token enum class level : std::uint8_t ^ lwlog/src/policy/../sinks/../level.h:20:12: error: ‘level’ does not name a type constexpr level operator|(level lhs, level rhs) ^~~~~ lwlog/src/policy/../sinks/../level.h:28:12: error: ‘level’ does not name a type constexpr level operator&(level lhs, level rhs) ^~~~~ lwlog/src/policy/../sinks/../level.h:39:27: error: ‘level’ was not declared in this scope constexpr bool has_level(level lhs, level rhs)
> 
> lwlog/src/policy/../sinks/../details/pattern/../os.h:19:45: error: ‘__SYS_gettid’ was not declared in this scope return static_caststd::size_t(::syscall(__SYS_gettid)); ^~~~~~~~~~~~ lwlog/src/policy/../sinks/../details/pattern/../os.h:19:45: note: suggested alternative: ‘SYS_gettid’ return static_caststd::size_t(::syscall(__SYS_gettid)); ^~~~~~~~~~~~ SYS_gettid In file included from lwlog/src/policy/../sinks/../details/pattern/pattern.h:8, from lwlog/src/policy/../sinks/sink.h:4, from lwlog/src/policy/log_policy.h:3, from lwlog/src/logger.h:3, from lwlog/lwlog.h:3, from log_test.cpp:1: lwlog/src/policy/../sinks/../details/pattern/../log_message.h: At global scope: lwlog/src/policy/../sinks/../details/pattern/../log_message.h:28:9: error: declaration of ‘lwlog::level lwlog::details::log_message::level’ [-fpermissive] level level;
> 
> im using ubuntu WSL on this machine Linux DESKTOP-M4HNI3V 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux

I fixed the error with SYS_gettid
But I'm honestly not sure what the other errors mean, I'm not used to GCC. But I can guess that it's because of the forward declaration of the level enum in the file fwd.h
