### ISSUE TITLE
Timestamp doesn't get updated through the logs

### ISSUE THREAD

**Issue by ChristianPanov** [ChristianPanov/lwlog#9]
The timestamp is only evaluated once, resulting in a singular timestamp that doesn't get updated.
The problem Is that the function **lwlog::details::datetime::format_time()** is too slow for it to be called on every log call.
It's execution is **~11μs**, which is far too much if we want a log call to remain **~8μs/~10μs**. A workaround needs to be found.

**Comment by smalls12** [comment]
An interesting topic, do you have any ideas?

**Comment by ChristianPanov** [comment]
It is very interesting indeed.
Well the very first thing that came to my mind is putting formatting on a background thread. However, I don't want to go that route, since here we are talking about synchronous logging, and I'm not sure if I can take such freedoms.
The thing is that obviously getting the time is just expensive. And I'm not sure if my get_time function is just inefficient, or that's just the way things are with time. If there was room for improvement in the function, maybe it could be optimized. 
If not, then an idea would be to do what I did with the color formatting - format it in place in the set_pattern() function directly. The problem with that is that time is relative to the log function call, so we won't get the correct time. Everything I've said so far is obvious. If only time was some value in memory that we could just get the address of it would have been much easier.
We have two options: 
- _optimize get_time, so it gets called when the log function is called without TOO much overhead_
- _do some trickery to divert the overhead of calling get_time into the set_pattern function_

And yet again, that's obvious stuff. So currently I don't have any actual ideas regarding the execution. I have ideas about the approach, but that's far from enough.
I am currently waiting for MSVC to implement chrono's new calendars and time zones, so I can see if they are dealing with time more efficiently, maybe that could save the day. Although that would make the library to be c++20 dependant, and I'm not going to be doing this. However, it will be a good start.
